services:
  php: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8
    volumes:
      - .:/var/www/html
      - ./apache:/etc/apache2/sites-available
    ports:
      - "8080:80"
    networks:
      - app
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DEVELOPMENT: ${DEVELOPMENT}
  db:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db_data:/var/lib/mysql
      - ./mysql/migrations:/docker-entrypoint-initdb.d
    networks:
      - app

networks:
  app:
    driver: bridge

